vanadium/core

go/src/v.io/x/ref/runtime/internal/address_chooser.go
go/src/v.io/x/ref/runtime/internal/cloudvm/cloud_linux.go
go/src/v.io/x/ref/runtime/internal/cloudvm_linux.go

The current behavior for Vanadium programs servers running on EC2 or GCE is to
detect the external IP and only use that. This is limiting because in many
realistic scenarios we want to be able to use both the local IPs and the
external IPs.

Add support for private IPs for EC2 and GCE VMs

---

x/ref/envvar.go
x/ref/services/agent/agentlib/principal.go

This commit allows disabling locking the credentials directory when
V23_CREDENTIALS_NO_LOCK environment variable is defined. This is useful when
the credentials are stored in a read-only location.
A realistic use case is when a Vanadium program is package in a Docker image
that doesn't have v23agentd and the credentials are mapped read-only using the
`docker run -v ...:ro`. In this case both V23_CREDENTIALS_NO_AGENT and
V23_CREDENTIALS_NO_LOCK need to be set. This can be done either in the
Dockerfile or via:
docker run \
--env V23_CREDENTIALS_NO_AGENT=1 \
--env V23_CREDENTIALS_NO_LOCK=1 \
...

Add an env variable to avoid locking the credentials directory

---

v23/flow/model.go
v23/rpc/model.go
v23/rpc/reflect_invoker_test.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/rpc/server.go
x/ref/runtime/protocols/debug/debug.go
x/ref/runtime/protocols/lib/tcputil/tcputil.go
x/ref/runtime/protocols/lib/websocket/conn.go
x/ref/runtime/protocols/local/init.go
x/ref/runtime/protocols/vine/vine.go
x/ref/services/mounttable/mounttablelib/mounttable_test.go

The v23/rpc/server/ServerCall interface doesn't expose via the
RemoteEndpoint() the real external address of the peer. This change
adds a RemoteAddr() method that does that.

Expose the real external address of a peer for a Vanadium call

---

v23/flow/model.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/services/xproxy/xproxy/proxy.go

The existing logic to avoid fragmentation from flw.writeMsg doesn't
always work causing the xproxy to send to peers (either clients or
servers) incorrectly fragmented messages. As far as I can tell this
happens because the xproxy uses asymmetric connections: the one from
clients/servers to xproxy is *conn.flw while the one from xproxy to
clients/server is tcputil.tcpConn. This, in turn, is causing the
Conn.setup from x/ref/runtime/internal/flow/conn/auth.go to not be able
to detect that encryption is disabled which is the trigger used for
allowing or not the fragmention.
The solution in this commit is to add a dedicated function to disable
fragmentation and use it in the xproxyd code. I did not use chose to
export and use the existing flw.disableEncryption because in this case
we are not …

Fix a fragmentation bug exhibit by xproxyd

---

x/ref/runtime/internal/rpc/typecache.go

Wrap intermittent nil pointer dereference with a nil check in `typeCache.collect()`.
Fix #24

Wrap intermittent nil pointer dereference with a nil check

---

v23/services/http/http.vdl
v23/services/http/http.vdl.go

This allows controlling the permissions for the `__debug/http` service
via the `-v23.permissions.literal` and `-v23.permissions.file` flags.

Add the Debug tag to the __debug/http service

---

x/ref/cmd/vrpc/vrpc.go
x/ref/lib/vdl/codegen/vdlgen/const.go

This feature make it possible to use the vrpc tool in programs like R or
in conjunctions with tools that know how to filter and process JSON
output (jq for example).
Internal GRAIL revisions: D3579, D10524.

Add support for JSON output to the vrpc tool

---

x/ref/examples/main.go
x/ref/examples/noflags/main.go
x/ref/internal/logger/logger.go
x/ref/lib/flags/flags.go
x/ref/runtime/factories/library/library.go

This pull request creates a new Vanadium factory that's suitable for use when creating Vanadium libraries. The main difference is that configuration is via export variables rather than command line flags.

v.io/x/ref/factories: add a factory for use when creating Vanadium libraries

---

x/ref/lib/flags/flags.go
x/ref/runtime/factories/library/library.go

Make it possible to specify multiple default namespace roots. Ideally these should come from a per-installation data file that's easy to version control locally, but for now they remain hard wired.

x/ref/lib/flags: allow specification of multiple default namespace roots

---

v23/context/context.go
v23/context/gcontext_test.go

This allows converting a context.Context of unknown origin to vanadium
*Context.T.
Background: if a library (outside v.io) is given a *vcontext.T, and it wraps the
context around context.{WithCancel,WithDeadline,WithValue}, then the context can
no longer be passed back to vanadium functions. This change allows for such
conversions.

v23/context: add FromGoContext to allow for conversion to/from context.Context

---

x/ref/runtime/internal/flow/conn/conn.go

Use ctx.VI(0).Infof rather than vlog.... to avoid introducing an unnecessary direct dependency.

/x/ref/runtime/internal/flow/conn: use ctx based logging, not vlog

---

v23/flow/model.go
x/ref/runtime/internal/flow/conn/auth.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/manager/conncache.go
x/ref/runtime/internal/flow/manager/manager.go
x/ref/runtime/internal/naming/namespace/all_test.go
x/ref/runtime/internal/rpc/client.go
x/ref/runtime/internal/rpc/server.go

There are three race conditions that are addressed by this pull request that would show themselves in rare failures for the TestAuthorizationDuringResolve (naming/namespace) test when the tests are run on a heavily loaded. It was possible to repro them using as well as seeing them on travis at peak load times during the day, but not evenings/weekends.
$ seq 1 2000 | parallel -j 30 'go test -v -run=TestAuthorizationDuringResolve -count=1
- dialing a side channel via DialSideChannel is racy in that it relies on finding the same connection, in the cache, as the existing parent connection (see rpc/client.go:479 and below). The connection cache may end up with multiple entries for the same remote endpoint depending on relative arrival of messages, but the existing code would return only the …

x/ref/runtime/internal: fix flaky tests due to rare race conditions in the networking layer

---

x/ref/runtime/factories/roaming/roaming.go

PR vanadium/go.lib#24 requires that os specific network configuration monitoring be explicitly enabled. This PR does so for the roaming profile.

x/ref/factories/roaming: explicitly enable netconfig for use with roaming

---

v23/query/engine/internal/query_checker/query_checker_test.go
v23/query/engine/internal/query_functions/query_functions_test.go
v23/query/engine/internal/query_parser/query_parser_test.go
v23/query/engine/query_test.go
v23/query/syncql/error_offset_test.go
v23/rpc/reflect_invoker_test.go
x/ref/cmd/namespace/impl.go
x/ref/cmd/principal/main.go
x/ref/runtime/factories/roaming/roaming-cgo.go
x/ref/runtime/factories/roaming/static.go
x/ref/runtime/factories/static/static.go
x/ref/runtime/internal/loadbalancing_test.go
x/ref/services/mounttable/mounttabled/main.go
x/ref/test/v23test/v23test.go

The roaming profile uses x/lib/osnetconfig to detect and read networking changes. osnetconfig requires the use of cgo which implies that any user of the roaming profile cannot be cross-compiled. This PR uses build constraints to disable the use of osnetconfig when cross compiling.
In addition, a new factory, static, is provided that explicitly does not enable roaming and it used where appropriate.

x/ref/runtime/factories: changes to support cross-compilation

---

x/ref/services/agent/agentlib/principal_v23_test.go

This change ensures that V23_CREDENTIALS_NO_LOCK is never set for this test and any subprocesses
that it runs. If it is set, even as V23_CREDENTIALS_NO_LOCK=0, then the test will fail. Another option would be to skip the test if env var is set.

x/ref/services/agent/agentlib: make sure that agent locking is always enabled for tests.

---

x/ref/cmd/principal/caveat.go
x/ref/cmd/principal/doc.go
x/ref/cmd/principal/main.go

This revisions uses the new flagvar support in x/lib/cmdline to modularalize flag handling for the principal command. The principal command was converted first to validate the new support. Things to note are the use of struct embedding to avoid duplication.

x/ref/cmd/principal: use x/lib/cmd.flagvar to modularalize flag handling

---

x/ref/cmd/principal/main.go

The wrapping was off in the text for `<principal to bless>`.
Before this commit:
```
<principal to bless> represents the principal to be blessed (i.e., whose public key will be provided with a name).  This can be either: (a) The directory containing credentials
for that principal, OR (b) The filename (- for STDIN) containing the base64url-encoded public
key or any other blessings of the principal,
OR (c) The object name produced by the 'recvblessings' command of this tool
running on behalf of another principal (if the --remote-key and
--remote-token flags are specified).
OR (d) None (if the --remote-arg-file flag is specified, only <extension> should be provided
to bless).
```
After this commit:
```
<principal to bless> represents the principal to be blessed (i.e., whose public key will …
```

Improve the `principal help bless` message

---

go.mod
x/ref/lib/flags/sitedefaults/go.mod

This submodule will allow users to replace the sitedefaults package with their local copy.
We will also need to tag this commit with x/ref/lib/flags/sitedefaults/v0.1.0

Add a sitedefaults submodule

---

x/ref/examples/echo/echo/echo.go
x/ref/examples/echo/echod/echod.go

The included cleanups are:
- switch to v.io/x/ref/runtime/factories/roaming
- add a name flag to echod and make it consistent with echo
- add the user in the name flag to avoid conflicts between users
- fix a typo in a comment.

Some cleanups for x/ref/examples/echo

---

x/ref/runtime/factories/library/library.go
x/ref/runtime/internal/rpc/server.go

The previous code required --v=1 or greater on the command line before it would display errors about an attempt to bind an in-use port. This revision changes that to always display the error.

x/ref/runtime/internal/rpc: always print errors returned by net.Listen

---

x/ref/runtime/factories/library/library.go

Ensure that command line flags on the flag.CommandLine flagset are parsed before they are actually used.

x/runtime/factories/library: ensure flags are parsed before use

---

v23/model.go
v23/security/access/authorizer.go
x/ref/examples/echo/echod/echod.go
x/ref/lib/flags/flags_test.go
x/ref/lib/flags/permissions.go
x/ref/lib/security/securityflag/flag.go
x/ref/runtime/factories/generic/generic.go
x/ref/runtime/factories/library/library.go
x/ref/runtime/factories/library/library_test.go
x/ref/runtime/factories/roaming/roaming.go
x/ref/runtime/factories/static/static.go
x/ref/runtime/internal/rpc/benchmark/benchmarkd/main.go
x/ref/runtime/internal/rpc/resolve_test.go
x/ref/runtime/internal/rt/runtime.go

warn the user if permissions are configured on the command line but not used by an authorizer. The warning could be spurious if multiple servers are created, one of which uses the permissions, but the others don't etc. However, this does cover the vast majority of common use cases.

v.io/x/ref/runtime: warn the user if command line permissions are not used

---

v23/context/context.go
v23/context/context_test.go
x/ref/lib/flags/sitedefaults/go.mod

Fix a bug calling WithRootCancel w/ a context created by FromGoContext will
cause the cancellation handler to be attached to FromGoContext context, not the
root one.
The problem is that WithRootCancel walks up the "parent" link to find the root.
But this chain breaks at FromGoContext. So it mistakesly assumes that the
FromGoContext context is the root.
This change fixes the problem by explicitly storing the pointer to root
cancelState in a context value.

context.WithRootCancel: fix interaction w/ FromGoContext

---

x/ref/cmd/vdl/vdl_test.go

This fixes a unit test that breaks with go 1.12.5. I'm not sure why it worked before though. The correct usage is: `vdl generate -v ...` and not `vdl -v generate`, or `vdl -v=2 generate -v=true`.

v.io/x/ref/cmd/vdl: fix test

---

.travis.yml
Makefile
go.mod
go.sum
x/ref/cmd/vdl/doc.go
x/ref/cmd/vdl/main.go
x/ref/lib/vdl/build/build.go
x/ref/lib/vdl/build/build_test.go
x/ref/lib/vdl/build/support_test.go
x/ref/lib/vdl/testdata/arith/arith.vdl.go
x/ref/runtime/internal/rpc/testutil_test.go
x/ref/runtime/internal/rt/rt_test.go
x/ref/runtime/internal/rt/shutdown_test.go
x/ref/services/identity/internal/revocation/revocation.vdl.go
x/ref/services/role/roled/internal/internal.vdl.go
x/ref/test/init.go

This PR provides go 1.14 compatibility. There are two changes:
1. calls to testing.Init() to initialize flags as required for regression tests
2. in celebration of go modules being declared 'production' ready, ensure that vdl can operate in a go module directory structure.

go1.14 support

---

.circleci/config.yml

Use circleci for tests and linting. However, the lint tests do not need to pass for a PR to be merged. This will be changed in a subsequent PR when the lint tests pass.

test,lint: use circleci for CI tests and lint

---

x/ref/lib/vdl/codegen/java/util_val.go

For float values that don't have '.' the code is appending a '.0'. The bug is
that we only need to do this if there are no exponents. When we have an
exponents appending the '.0' is generating invalid numbers (like '5e-203.0'
instead of '5e-203').

x/ref/lib/vdl/codegen/java: fix for handling certain float values

---

.circleci/config.yml
v23/flow/message/message.go
x/ref/runtime/internal/flow/conn/auth.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go

See issue #132 for a more complete description of the background to this PR. In summary, this PR makes the following changes.
1. ensures that the client RPC dial handshake code acts on errors returned by the handshake process even if that handshake is
interrupted by a context cancelation.
2. the code that reads auth blessings (readRemoteAuth) explicitly handles connection teardown messages and reports a closed connection rather than silently closing the connection and reporting an EOF error on the first read.
3. minor changes to expose the flow id via APIs to help with debugging in future.

x/ref/runtime/internal/flow/conn: fix flaky test

---

x/ref/examples/tunnel/tunneld/main.go
x/ref/lib/signals/signals.go
x/ref/lib/signals/signals_test.go
x/ref/runtime/internal/rpc/benchmark/benchmarkd/main.go
x/ref/runtime/internal/rt/shutdown_servers_test.go
x/ref/services/groups/groupsd/main.go
x/ref/services/xproxy/xproxyd/main.go
x/ref/test/hello/helloserver/helloserver.go

The shutdown function returned by v23.Init() keeps track of all services and will wait for them to be terminate, it does not explicitly initiate their shutdown however since the idiomatic way to do so is by canceling their context. Many servers wait for an OS signal before terminating using the signals.ShutdownOnSignals but often neglect to cancel the context used to create runtime services. `signals.ShutdownOnSignalsWithCancel(ctx)` is provided to make such cleanup more easily used. The following code will both wait for a signal, cancel the context when a signal is received thus initiating the shutdown of all services created using that context.
```go
ctx, shutdown := test.V23Init()
defer shutdown()
ctx, waitForSignal := signals.ShutdownOnSignalsWithCancel(ctx)
// use ctx when creating …
```

x/ref/lib/signals: add the ability to react to context cancelation and to cancel a context on a signal reception

---

x/ref/examples/tunnel/tunneld/main.go
x/ref/lib/signals/signals.go
x/ref/lib/signals/signals_test.go
x/ref/runtime/internal/rpc/benchmark/benchmarkd/main.go
x/ref/runtime/internal/rt/shutdown_servers_test.go
x/ref/services/groups/groupsd/main.go
x/ref/services/xproxy/xproxyd/main.go
x/ref/test/hello/helloserver/helloserver.go

Revise the signals API to allow for registering additional cancel functions to be called when a signal is received or the context canceled. It also seems more obvious to call handler.WaitForSignals() rather than 'functionName()' to wait for signals.

x/ref/lib/signals: update signals API

---

x/ref/envvar.go
x/ref/lib/security/blessingroots.go
x/ref/lib/security/blessingstore.go
x/ref/lib/security/internal/lockedfile/mutex.go
x/ref/lib/security/principal.go
x/ref/lib/security/principal_test.go
x/ref/lib/security/util.go

This PR changes the locking strategy to use a read-only lock for read/loading principals versus a read-write lock for mutation. This should allow for servers to be run with read-only filesystems hosting their credentials. It also adds an environment variable V23_CREDENTIALS_READONLY_FILESYSTEM to specify when credentials are on a read-only filesystem, the previous V23_CREDENTIALS_NO_LOCK is now an alias for the former and will be deleted in the future.

x/ref/lib/security: use read-only lock for reading/loading principal data.

---

v23/context/context.go
v23/context/context_test.go
v23/context/internal_test.go
v23/context/wraplog.go

Add `context.WithLoggingPrefix(*T, interface{})` to allow setting a context mediated 'prefix' to be prepended to every line of log output generated via the implementation of logging.Logger provided by context.T. This should make it straightforward for example to prepend all log entries generated for a specific operation or RPC request with an id unique to that operation/request.

v23/context: add a logging prefix to context based logging.

---

v23/verror/pkgpath.go
v23/verror/pkgpath_test.go
v23/verror/verror.go
v23/verror/verror_id_test.go
x/ref/runtime/internal/flow/util.go
x/ref/runtime/internal/flow/util_test.go

It was a mistake to use go.mod files at runtime since they are likely not present when apps are actually run!

v23/verror: fix how default verror package paths are calculated

---

.circleci/config.yml
go.mod
go.sum

1.15.4 fixes the cgo bug in .3 that broke openssl integration.

update go go1.15.4 and v.io/x/lib 0.1.7

---

x/ref/runtime/internal/cloudvm.go
x/ref/runtime/internal/cloudvm/aws.go
x/ref/runtime/internal/cloudvm/aws_test.go
x/ref/runtime/internal/cloudvm/cloudvmtest/aws_mock.go
x/ref/runtime/internal/cloudvm_test.go

AWS' instance meta data service cannot be accessed from a docker container running in bridge mode. This PR changes the behaviour to use the v1 service first and only if that fails, to use the v2 service. This fallback is required since it's possible to
configure aws instances to allow v2 only.

x/ref/runtime/internal: use aws imds v1 first and then v2

---

v23/verror/verror.go

Using FuncForPC is deprecated and the problems cited for it show themselves on darwin/arm64 platforms. With this PR all tests apart from openssl,  and v.io/x/ref/services/debug/debug -v23.tests  pass on Apple's A12 based mac-mini.

v23/verror: use CallersFrames rather than FuncForPC

---

v23/verror/verror.go
x/ref/services/internal/logreaderlib/logfile.go

os.Readdir will stop enumerating entries on encountering a permissions error, however there may be subsequent entries that can be read. This PR calls Readdir multiple times until io.EOF is returned even if an error is encountered. It returns the last error
it observes and streams all entries returned by Readdir. This was encountered on apple silicon mac mini, but it's likely due to Big Sur rather than the hardware so will likely be encountered more broadly than apple silicon machines.

x/ref/services/internal/logreaderlib: ensure that all entries are read even in the face of a permissions error.

---

v23/vom/internal/bench_test.go
v23/vom/internal/internal.vdl.go
v23/vom/internal/types.go
v23/vom/internal/types.vdl
v23/vom/internal/vombenchgen/gen.go

This PR updates the existing benchmarks to include vdl optional and native types. It turns out these are significantly slower than they could be and become apparent when benchmarking vdl/vom against other encodings. Subsequent PRs will address the actual performance issues.

v23/vom/internal: update benchmarks to include optional and native types.

---

x/ref/runtime/internal/rpc/proxymgr.go
x/ref/runtime/internal/rpc/proxymgr_test.go
x/ref/runtime/internal/rpc/test/client_test.go
x/ref/services/xproxy/xproxyd/proxyd_v23_test.go

Prior to this PR, a server using the 'all' proxy policy would expand the set of proxy instances that it used when it encountered an error with any of existing proxy instances. This PR changes the behavior so that servers will monitor the set of available proxy instances and expand to use all available ones ahead of any errors being encountered.
Also, include a fix for big sur whereby the error messages for connection refused appears to have changed.

x/ref/runtime/internal/rpc: ensure that a proxied server expands to use all available proxies

---

v23/vom/vomtest/internal/vomforever/main.go
x/ref/lib/publisher/publisher.go
x/ref/lib/pubsub/publisher.go
x/ref/runtime/factories/roaming/print_addrs.go
x/ref/runtime/internal/rpc/proxymgr.go
x/ref/runtime/protocols/lib/websocket/conn_test.go
x/ref/runtime/protocols/lib/websocket/listener.go

This PR reduces the amount of info-level logging output from lib/publisher and rpc/proxymanager.

x/ref/runtime/internal/rpc,x/ref/lib/publisher: reduce default logging output

---

README.md
v23/namespace/model.go

Update the README link to v23 site such that Github will not parse it
as a file in the repository.
Update docs for namespace.T.Glob() method to refer to the
GlobReplyEntry and GlobReplyError return types, both in the docstring
and in the given example.

fix README link and namespace.T.Glob() docs

---

x/ref/examples/echo/bin/Dockerfile.echo
x/ref/examples/echo/bin/Dockerfile.echod
x/ref/examples/echo/bin/Dockerfile.mounttabled
x/ref/examples/echo/echo/echo.go
x/ref/examples/echo/echod/echod.go
x/ref/lib/aws/vxray/config.go
x/ref/lib/aws/vxray/internal/eks_info.go
x/ref/lib/aws/vxray/manager.go

This PR adds support for obtaining the eke/kubernetes(k8s) cluster name, container id etc. Note, this is PR is not specific to EKS and can be used for other k8s systems. It relies on the convention that the k8s cluster is configured to write a configmap with the cluster's name as one of the key/value pairs. The vxray setup allows for both the name of the configmap and the key for the cluster name to be configured.

x/ref/lib/aws/vxray: add support for obtaining eks/k8s data

---

v23/context/context.go
v23/context/context_test.go

Whenever a child context is created via `WithRootCancel`, a goroutine
spawns to gracefully handle closing the child context whenever the root
context gets canceled.
However, the current implementation leaks goroutines whenever the child
context exits before the root context exits. This pull request looks to
fix the problem by exiting the goroutine whenever the child context is
done.
See `TestRootCancelGoroutineLeak` for the reproduction use case and test
that demonstrates the leak. This is also easily visible via `pprof`
using the `goroutine` module.
Fix #1419

v23/context: fix goroutine leak in WithRootCancel

---

v23/context/context.go
v23/context/context_test.go

incorporate PR's #214 and #215 into 1.18 release to create 1.19.

v0.1.19: incorporate PR's #214 and #215 into 1.18 release to create 1.19

---

.circleci/config.yml
x/ref/lib/aws/vxray/manager.go
x/ref/lib/aws/vxray/vxray_test.go

aws/aws-xray-sdk-go#51 describes the goroutine leak in xray.BeginSegmentWithSampling and an appropriate fix (Cyberax/aws-xray-sdk-go@033bad5). However, a different, incomplete fix was adopted: https://github.com/aws/aws-xray-sdk-go/pull/156/files.
This PR works around this bug by artificially creating a context and then canceling that new context when the xray segment is closed.

x/ref/lib/aws/vxray: work around goroutine leak in xray.BeginSegmentWithSampling

---

x/ref/lib/pubsub/config_test.go
x/ref/lib/security/blessingstore.go
x/ref/lib/security/principal.go
x/ref/runtime/internal/lib/sync/semaphore_test.go
x/ref/services/internal/pproflib/proxy_test.go

This PR fixes the pubsub test that can flake on very slow systems:
- x/ref/lib/pubsub
- x/ref/services/internal/pproflib
- x/ref/lib/security
It also fixes x/ref/runtime/internal/lib/sync to avoid calling t.Fatal from a goroutine which lint now, correctly, complains about.

fix flaky/incorrect tests

---

v23/model.go
v23/rpc/model.go
v23/vom/decoder_test.go
x/ref/cmd/principal/internal/scripting/scripting_test.go
x/ref/cmd/vrpc/vrpc.go
x/ref/cmd/vrpc/vrpc_test.go
x/ref/lib/discovery/advertise_server.go
x/ref/lib/discovery/directory.go
x/ref/runtime/internal/rpc/server.go
x/ref/runtime/internal/rpc/test/server_test.go
x/ref/test/testutil/rpc.go

The decode tests in v23/vom fail very rarely for unknown reasons on slow CI systems, this PR adds additional debugging to help track that down.
The state transitions for an RPC server are racy in the sense that there is a lot of code between the server being created, initializing itself and being read to accept requests. This seems to show up in some tests where the client code attempts to connect to the server while it is still initializing. This PR changes the states to Initialiazing, Ready, Stopping, Stopped from Active, Stopping and Stopped. A testutil function WaitForServerReady is provided for clients to wait for a server to be ready before attempting to use it, though this only really an issue for tests.
Similarly, the proxyd tests sometimes fail with a panic on slow systems and …

v23/vom,v23/rpc,v23: additional debugging, more conservative locking

---

x/ref/lib/security/blessingroots.go
x/ref/lib/security/blessingstore.go
x/ref/lib/security/internal/lockedfile/mutex.go
x/ref/lib/security/principal_test.go
x/ref/lib/security/util.go
x/ref/runtime/internal/loadbalancing_test.go
x/ref/runtime/internal/rpc/test/client_test.go
x/ref/runtime/internal/rpc/test/full_test.go
x/ref/runtime/protocols/lib/websocket/listener_test.go
x/ref/runtime/protocols/lib/websocket/ws_test.go
x/ref/test/goroutines/goroutines_test.go

This PR fixes a flaky test by waiting for the expected changes to take place. Issue #236 calls for a better mechanism for doing so.
Tight timeouts are extended in the rpc tests.
Also, add the O_CREATE flag when creating read-only locks to cleanup unnecessary complexity in the code that uses the internal lockedfile package.

x/ref/lib/security,x/runtime: fix flaky tests, including TestDaemonMode and overly tight timeouts in RPC tests.

---

x/ref/lib/security/ssl_test.go

Fix TestLetsEncryptKeys to use a fixed time for validating the test certificate to avoid an unnecessary expired certificate error.

x/ref/lib/security: fix out of date SSL cert test

---

x/ref/cmd/principal/doc.go
x/ref/cmd/principal/main.go
x/ref/cmd/principal/principal_v23_test.go
x/ref/lib/security/create_principal.go
x/ref/lib/security/create_principal_opts.go
x/ref/lib/security/keyfile_util.go
x/ref/lib/security/keys/internal/key_util.go
x/ref/lib/security/keys/sshkeys/agent_test.go
x/ref/lib/security/keys/sshkeys/ssh_import.go
x/ref/lib/security/keys/sshkeys/ssh_import_test.go
x/ref/lib/security/keys/sshkeys/sshkeys.go
x/ref/lib/security/keys/x509keys/x509_import.go
x/ref/lib/security/keys/x509keys/x509_import_test.go
x/ref/lib/security/keys/x509keys/x509keys.go
x/ref/lib/security/keys/x509keys/x509keys_test.go
x/ref/lib/security/principal_test.go
x/ref/lib/vdl/parse/grammar.y.go

This PR deletes unnecessary code intended for importing existing existing keys when creating vanadium principals. The principal command is simplified to use CreatePrincipalOpts and can now use external ssh and ssl private keys, or copy them into the principal's credentials directory, as well as creating new keys and using private keys hosted in ssh agents.

x/ref/lib/securitykeys/...,x/ref/cmd/principal: clean up creating principals and importing keys.

---

v23/flow/message/internal_message_test.go
v23/flow/message/message.go
v23/flow/message/message_test.go
x/ref/runtime/internal/rpc/test/compatibility_v23_test.go

This PR adds the ability to use ED25519 and RSA keys to authenticate RPC. This requires extending the RPC auth message to carry the new signature types. This is done in a backwards compatible manner.
Tests are included for the expected errors for different combinations of crypto keys against the v0.1.20 release. ED25519 keys used by a server will lead to a client side protocol error. RSA keys cannot be loaded by earlier releases and such applications will fail when loading a principal that contains an RSA key as either a private key or when loading a RSA public key added as a blessing root.

x/ref/runtime/internal/rpc/test: add ED25519 and RSA signatures to the RPC protocol.

---

Makefile

Add the backwards compatibility integration test to the top-level Makefile.

x/ref/runtime/internal/rpc/test: add to Makefile

---

x/ref/lib/security/keys/sshkeys/agent.go
x/ref/lib/security/keys/sshkeys/agent_client.go
x/ref/lib/security/keys/sshkeys/agent_test.go
x/ref/lib/security/keys/sshkeys/sshkeys.go

There was a rare race between zeroing out the passphrase stored in the ssh agent signer implementations via its finalizer and it being used by the signer implementation in a deferred function. This PR simplifies this logic and hopefully avoids the race by not having the signer zero out the passphrase, rather, it keeps a reference to the HostedKey which creates the signer and accesses the passphrase directly from that key.

x/ref/lib/security/keys/sshkeys: fix racy test

---

x/ref/lib/security/keys/sshkeys/agent.go
x/ref/lib/security/keys/sshkeys/agent_client.go

It seems too complicated to zero the agent passphrase automatically without creating a race. Consequently, the sshkeys package no longer attempts to zero the passphrase. This is not so bad since the passphrase is used to unlock/lock the ssh-agent and can be changed easily and frequently and is, in any case, only of value when agent forwarding is used. As more experience is gained with using different types of agent (eg. ones hosted in a Secure Enclave) the handling of the passphrase may also change.

x/ref/lib/security/keys/sshkeys: fix racy test again

---

v23/security/principal.go
x/ref/cmd/principal/main.go
x/ref/cmd/principal/principal_v23_test.go
x/ref/lib/security/create_principal_opts.go
x/ref/lib/security/keyfile_util.go
x/ref/lib/security/keys/x509keys/x509keys.go
x/ref/lib/security/options.go
x/ref/lib/security/principal.go
x/ref/lib/security/principal_opts_test.go
x/ref/lib/security/principal_test.go
x/ref/test/sectestdata/data_test.go
x/ref/test/sectestdata/ssh.go

This PR enables using x509 certificates as public keys. It also fixes some inconsistencies in how options to lib/security.CreatePrincipalOpts are handled and now has a clear precedence order for options. More tests for that use CreatePrincipalOpts are added.

x/ref/lib/security: enable use of x509 certs as public keys and add more tests for creating principals

---

v23/security/publickey.go
x/ref/lib/security/blessingstore.go
x/ref/lib/security/create_principal_opts.go
x/ref/lib/security/keyfile_util.go
x/ref/lib/security/keys/registrar.go
x/ref/lib/security/options.go
x/ref/lib/security/principal_opts.go
x/ref/lib/security/principal_opts_test.go
x/ref/lib/security/principal_store.go

The existing API for loading an existing principal did not allow for using a custom blessing store or blessing root due to the need for those stores to have access to the key information to allow for signing/verification changes to the stores. And since this information is not available prior to loading or outside of the principal it's not possible to create a store externally. This PR fixes this by allowing for a function to be specified as an option to LoadPrincipalOpts which is invoked with the appropriate signer and/or public key to allow for custom stores to be created. It also allows for an x509 certificate to be extracted from a public key that is stored as a certificate.

x/ref/lib/security: allow for LoadPrincipalOpts to use custom blessing store and blessing roots.

---

x/ref/aws/go.sum

Remove go.sum entry that's causing a dependabot warning.

x/ref/aws: update dependencies

---

v23/verror/compat.go
v23/verror/verror_errorf_test.go

Support `errors.Is` matching of chained errors.  That is:
```go
err := errors.New("test error")
errors.Is(verror.Errorf(nil, "wrapping: %v", err), err) // true
```

v23/verror: support chain matching with errors.Is

---

x/ref/runtime/internal/flow/conn/close_test.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go

This PR addresses #285 by deleting the per-flow flow control counters maintained by the underlying connection when a flow is closed.

x/ref/runtime/internal/flow: delete flow control counters when a flow is closed

---

x/ref/runtime/internal/flow/conn/close_test.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/rpc/benchmark/benchmark/doc.go
x/ref/runtime/internal/rpc/benchmark/benchmarkd/doc.go

PR #287 deleted the toRelease/borrowed entries for a flow when it is closed. This greatly reduced the size of the Release messages for the common case. However, those counters are required when borrowed is true past the flow being closed so that the dialer can recover the borrowed tokens to its shared pool of tokens. In cases where a great number of short lived connections are created the resulting Release message can be larger than the default buffer size allowed and hence will require fragmentation. When routed through a proxy these large messages can lead to deadlock since the proxy's encapsulate flow will not forward a message that has to be fragmented if it does not have enough flow control counters for the entire message. This PR explicitly fragments the Release message to get …

x/ref/runtime/internal/flow/conn: fragment release message

---

v23/flow/message/message_test.go
v23/rpc/version/version.go
x/ref/runtime/internal/flow/conn/auth.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/conn_test.go
x/ref/runtime/internal/flow/conn/util_test.go
x/ref/runtime/internal/flow/manager/conncache_test.go
x/ref/runtime/protocols/local/init.go

This PR cleans up version number error checking and in tests in preparation for using a new version in the (not so distant) future.

v23/rpc/versions,x/ref/internal/runtime/internal: clean up version handling

---

v23/naming/endpoint.go
v23/naming/endpoint_test.go
v23/naming/parse_test.go

This PR reduces the number of memory allocations required for parsing endpoints in two ways:
1. providing a ParseEndpointBytes functions which avoids the caller having to convert a []byte to
a string prior to calling ParseEndpoint as happens within the rpc runtime in many places.
2. avoid splitting on the @ separator in parse6 and rejoining/splitting again.

v23/naming: reduce the number of memory allocations required for parsing endpoints

---

x/ref/runtime/internal/rpc/benchmark/internal/client.go

This PR includes a change that was missed from #290 that allows the benchmarks in benchmark/summary to be run without producing histograms.

x/ref/runtime/internal/rpc/benchmark/internal: fix summary benchmark

---

x/ref/lib/discovery/plugins/ble/ble.go
x/ref/lib/discovery/plugins/testutil/util.go
x/ref/lib/discovery/trigger.go

This PR stops the discovery Trigger when the ble plugin is stopped. This bug was noticed while debugging the flaky failures of the ble tests. This fix should reduce the number of outstanding goroutines when the tests do fail. Additional logging is added to help track down the cause of the failures which take the form of the tests running for longer than 10 minutes which suggests some kind of deadlock in the tests or the ble code since the tests generally run in .1 or .2s.

x/ref/lib/discovery/plugins/ble: stop the discovery Trigger.

---

v23/context/context_test.go
x/ref/test/goroutines/goroutines.go
x/ref/test/goroutines/goroutines_test.go

This PR attempts to de-flake TestRootCancelGoroutineLeak and makes some minor changes to the leak detection code (NoLeaks) to display the timeout and fail if it fails to parse the goroutine state output.

v23/context: de-flake TestRootCancelGoroutineLeak

---

v23/flow/message/message.go
v23/flow/message/message_test.go
v23/naming/endpoint.go
v23/naming/endpoint_test.go

This PR uses strings.Builder to implement naming.Endpoint.String() to reduce the number of allocations required and to improve its performance. Similarly the implementation of the flow/message is improved to avoid unnecessary copies when serializing and parsing endpoints. Appending a setup message now requires 11 allocations vs 31 before this PR.

v23/naming,v23/flow/message: reduce mem allocations of using Endpoints

---

v23/flow/message/message.go
v23/flow/message/message_test.go
v23/naming/endpoint.go
v23/naming/endpoint_test.go

This PR adds message.CopyBuffers in anticipation of experimenting with using shared buffers for network input. CopyBuffers would be called to make copies of any internally use buffers that refer to the original buffer that the message
was read from. ParseEndpointBytes is also removed since it proved too hard to manage the lifecycle of endpoints. Finally, the order in the switch statement in message.Read is modified to have more commonly used messages first.

v23/flow/message,v23/naming: add message.CopyBuffers and remove naming.ParseEndpointBytes

---

v23/flow/model.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/protocols/debug/debug.go
x/ref/runtime/protocols/lib/framer/framer.go
x/ref/runtime/protocols/lib/framer/framer_test.go
x/ref/runtime/protocols/lib/websocket/conn.go
x/ref/runtime/protocols/local/init.go
x/ref/runtime/protocols/vine/vine.go

ReadMsg2 allows for the caller to supply a buffer to be (optionally) used instead of always allocating a new buffer for each new message. This is intended to support reducing memory allocations and copies in the RPC stack.

v23/flow: add ReadMsg2 to flow.MsgReader api

---

v23/flow/message/internal_message_test.go
v23/flow/message/message.go

This PR improves the performance of the varint read/write routines by unrolling loops. The new routines are about 3x faster and are faster for shorter as opposed to longer ints. To see the differences run the benchmarks: go test -bench=. - the previous code is retained for backwards compatibility testing.

v23/flow/message: improve the performance of the varint read/write routines.

---

x/ref/runtime/internal/rpc/benchmark/summary/summary_test.go
x/ref/runtime/protocols/lib/framer/framer.go
x/ref/runtime/protocols/lib/framer/framer_test.go
x/ref/runtime/protocols/lib/tcputil/tcputil.go

This PR ensures that the framer implementation will never use more than a fixed amount of memory. The previous implementation would always copy the supplied data to a newly allocated buffer in order to prepend the frame size before issuing a single system call to write the data. The new implementation instead will only do this for small payloads, for larger ones it will issue multiple system calls, one for the message size and then one per payload argument. This also reduces the amount of data copying which should be beneficial for large payloads.

x/ref/runtime/protocols/lib/framer: bound memory usage

---

x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/readq.go
x/ref/runtime/internal/flow/conn/readq_test.go

This PR tidies up and documents the implementation of the readq used to pass data from a flow's network receiver code to the flow's Read and ReadMsg methods used by higher level code. The current implementation assumes that buffers may be passed directly from the network to the readq and then on to the caller of GetMsg (called on a different goroutine) and this is now clearly documented/defined.

x/ref/runtime/internal/flow/conn: minor changes and comments for the readq implementation

---

x/ref/runtime/internal/flow/conn/auth.go
x/ref/runtime/internal/flow/conn/blessings_caches.go
x/ref/runtime/internal/flow/conn/blessings_caches_test.go
x/ref/runtime/internal/flow/conn/blessings_flow.go

This PR replaces the use of maps with slices for the caches used by the blessingsFlow implementation since in practice the number of elements stored is very small (typically 2) so using maps is expensive by comparison to small slices. Memory allocation is accordingly reduced.
The creation of blessingsFlows is also simplified.

x/ref/runtime/internal/flow/conn: refactor the blessingsFlow caches to be slices rather than maps

---

v23/vom/decoder.go
v23/vom/decoder_util.go
v23/vom/dump.go
v23/vom/single_shot.go

This PR makes error reporting more specific to help track down a flaky test failure of rpc/test/cancel_test:TestCancel.

v23/vom: make errors more specific and informative

---

v23/vdl/reflect_type_test.go
v23/vdl/type.go
v23/vdl/type_builder.go
v23/vom/type_encoder.go

This PR is similar to #316. Additional benchmarks show that on a M1 Macbook Pro slices with fewer than 32 entries easily outperform a map.

v23/vom: use slice instead of small maps for better performance and less memory overhead.

---

x/ref/runtime/internal/flow/conn/auth.go
x/ref/runtime/internal/flow/conn/close_test.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flowcontrol.go
x/ref/runtime/internal/flow/conn/handle_message.go

This PR separates out the flow control counters from the core Conn and Flow structs, moving into their own data types with specific locking for the flow control stats. This is a step towards simplifying the current locking strategy which relies on a single lock on the Conn to guard both the Conn and Flow's core data structures. The only shared state between a Conn and Flow are the flow control counters and by breaking this out it will allow for the simplification of both the Conn and Flow's locking going forward.

x/ref/runtime/internal/flow/conn: refactor flow control stats

---

v23/verror/compat.go
v23/vom/binary_util.go
x/ref/runtime/internal/flow/conn/readq.go
x/ref/runtime/internal/rpc/client.go
x/ref/runtime/internal/rpc/test/client_test.go

This PR attempts to fix the flaky RPC tests TestTimeoutResponse and TestStreamTimeout which sometimes fail with an EOF rather a timeout error. The attempted fix is in conn.readq.waitLocked which will now return a context.DeadlineExceeded error when the context contains that error rather than converting all context errors to EOF. Additional changes are required to unwrap the timeout error and act accordingly. In addition, the tests themselves are run with different timeouts and additional vtrace output to further diagnose the problem if it persists.

x/ref/runtime/internal/{flow/conn,rpc/test}: attempt to fix flaky test

---

x/ref/runtime/internal/rpc/client.go
x/ref/runtime/internal/rpc/test/client_test.go

This PR continues to clean up the flaky TimeoutResponse and StreamTimeout tests. It now pre-warms the connection by issuing a ping RPC first before initiating the timeout for the RPC that hangs.

x/ref/runtime/internal/rpc/test: continued attempt at fixing flaky test

---

x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flowcontrol.go

This PR continues to tidy up how flow control is implemented and moves the calculates for the available tokens out of the flw object and into the flowControlFlowStats object instead. Similarly the token adjustments when a flow is closed are moved into flowControlFlowStats.

x/ref/runtime/internal/flow/conn: relocate flow control token calculations

---

x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/handle_message.go

Flows may be created implicitly when accepted, or explicitly when dialed. A dialed flow must send an OpenFlow message to its peer, whereas an accepted flow is created in response to receiving an OpenFlow message. This PR consolidates the handling of these two cases and in particular the communication to the underlying Conn object's waitgroup that an explicitly created, dialed, flow has sent its OpenFlow message.

x/ref/runtime/internal/flow/conn: tidy up tracking of unopened to opened states for flows.

---

x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flowcontrol.go

This PR moves the flow control calculations for when tokens are released out of the flw object and into flowControlFlowStats.

x/ref/runtime/internal/flow/conn: move flow control token calculations.

---

x/ref/runtime/internal/flow/conn/buffer_pools.go
x/ref/runtime/internal/flow/conn/bufferingflow.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/message_pipe.go

Tidy up locking in message_pipe.go and conn.go; the latter using the more usual 'lock; defer unlock' pattern rather than 'defer unlock; lock'. It also moves all sync.Pools into a single file, buffer_pools.go.

x/ref/runtime/internal/flow/conn: tidy up locking and sync.Pools

---

x/ref/test/goroutines/goroutines_test.go

This PR fixes TestGet so that it leaves all goroutines running until the very last moment to ensure that they are running when the stacks are examined. Without this change it's possible for one of them to run to completion before the stack dump is taken.

x/ref/test/goroutines: fix flaky test

---

x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flowcontrol_test.go
x/ref/runtime/internal/flow/conn/readq.go

This PR is a follow-on to #322 that fixes a performance bug and reduces the overhead of sending blessings.
1. #322 inadvertently disabled sending data with an openflow message, this PR fixes that. Note that openflow messages do not wait for flow control tokens, but will simply send as much data as they can.
2. the blessingsflow.send method is only invoked when a flow is first opened thus saving the overhead of map lookups and key generation.

x/ref/runtime/internal/flow/conn: follow-on to PR #322

---

x/ref/runtime/internal/flow/conn/blessings_flow.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/writeq.go

There appears to be a race when connections enter lameduck mode and a flow is closed. Both require sending a message to the connection/flow's peer using conn.sendMessage. The message sent for lameduck mode via conn.handleEnterLameDuck is cancelable, whereas the one sent from conn.internalCloseLocked is not. This allows for a deadlock between the cancelable one attempting to acquire the writeq's lock in handleCancel, and the non-cancelable one calling writeq.wait and then writeq.done where it can block attempting to send over the channel for another writeq entry that has been canceled whilst holding the writeq's lock. The fixes are two fold:
1. never to hold the writeq's lock whilst sending over a channel
2. allow for writeq to be closed channels to be closed in addition to sending an …

x/ref/runtime/internal/flow/conn: fix race condition with canceled writeq entries

---

x/ref/runtime/internal/flow/conn/flowcontrol_test.go
x/ref/runtime/internal/flow/conn/writeq.go
x/ref/runtime/internal/flow/conn/writeq_test.go

This PR addresses a race condition in the writeq implementation between normal notification of writeq writers and cancelations of those writers. When cancelations are mixed in with normal operation the cancelations could lead to situations where the writeq invariants are violated. In particular, a writer may have both a normal notification and a cancelation in flight and the receiving select statement may chose one or the other. If it choses the cancelation then its necessary to drain the notification channel. Similarly, notifications are sent whilst holding the writeq's lock to ensure that only one notification may be sent at a time.

x/ref/runtime/internal/flow/conn: fix race condition in the writeq implementation

---

x/ref/runtime/internal/flow/conn/close_test.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flowcontrol.go
x/ref/runtime/internal/flow/conn/flowcontrol_invariants_test.go

This PR refactors the flow control data structures to avoid the need to use a map to track which flows are using borrowed tokens on their remote ends to reduce the storage/gc overhead of maintaining this map. It moves the state for tracking which flows have remote ends that are borrowing tokens to flowControlFlowStats from flowControlConStats.
It also clarifies the fact that the locking order should be connection first and then flow control.

x/ref/runtime/internal/flow/conn: refactor how 'remote borrowing' is tracked

---

x/ref/services/xproxy/xproxyd/proxyd_v23_test.go

This PR extends the timeout for gathering proxy stats to avoid the integration tests failing when run on very slow CI runner instances.

x/ref/services/xproxy/xproxyd: extend timeout to deflake test

---

x/ref/runtime/internal/flow/conn/writeq_test.go

This PR ensures that the TestWriteqErrors exits cleanly with all goroutines having exited.

x/ref/runtime/internal/flow/conn: fix TestWriteqErrors flaky test

---

x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/flow_test.go

This PR reimplements and renames 'popFront' as 'removeAtMost' to avoid unnecessary memory allocations. Instead of creating a new slice of byte slices it returns an index into the slice of slices and an offset into the current slice. This leads to many fewer allocations for large (greater than MTU) sized payloads. A 1MB message now needs 298 vs 328 allocations and a 10M message 980 vs 1282.

x/ref/runtime/internal/flow/conn: refactor and rename 'popFront'

---

x/ref/runtime/internal/flow/conn/flowcontrol_invariants_test.go
x/ref/runtime/internal/flow/conn/flowcontrol_test.go

This PR fixes a flaky test by having it wait for the expected invariant to become true.

x/ref/runtime/internal/flow/conn: fix flaky TestFlowcontrolCounters.

---

x/ref/runtime/internal/flow/conn/flowcontrol_invariants_test.go
x/ref/runtime/internal/flow/conn/flowcontrol_test.go
x/ref/runtime/internal/flow/conn/lameduck_test.go
x/ref/runtime/internal/flow/conn/writeq_test.go

This PR reduces the flakiness of TestWriteqErrors and improves the reporting offered by the 'waitFor' test utility function.

x/ref/runtime/internal/flow/conn: continued test improvements

---

x/ref/runtime/internal/flow/conn/flow_test.go
x/ref/runtime/internal/flow/conn/util_test.go
x/ref/runtime/internal/flow/flowtest/flowtest.go

The results of these show that the bulk of allocations are now on the receive side and will be addressed in subsequent PRs.

x/ref/runtime/internal/flow/conn: add benchmarks for Flows and BufferingFlows.

---

x/ref/runtime/internal/flow/conn/conn.go

This PR fixes NewAccepted to use a channel with a buffer size of 1 for use with acceptHandshake. Without this a deadlock can occur.

x/ref/runtime/internal/flow/conn: the handshake channel needs a buffer size of 1

---

v23/flow/model.go
v23/security/authorizer_test.go
v23/security/call.go
v23/security/call_test.go
v23/security/caveat_test.go
v23/security/discharge.go
v23/security/discharge_test.go
v23/security/init.go
v23/security/model.go
x/ref/lib/security/prepare_discharges.go
x/ref/lib/security/prepare_discharges_test.go
x/ref/runtime/internal/flow/conn/auth_test.go
x/ref/runtime/internal/flow/conn/blessings_caches.go
x/ref/runtime/internal/flow/conn/blessings_flow.go
x/ref/runtime/internal/flow/conn/conn.go
x/ref/runtime/internal/flow/conn/flow.go
x/ref/runtime/internal/flow/conn/util_test.go
x/ref/runtime/internal/flow/flowtest/flowtest.go
x/ref/runtime/internal/flow/manager/conncache.go
x/ref/runtime/internal/flow/manager/conncache_test.go
x/ref/runtime/internal/flow/manager/manager.go
x/ref/runtime/internal/rpc/client.go
x/ref/runtime/internal/rpc/server.go
x/ref/runtime/internal/rpc/testutil_test.go
x/ref/services/xproxy/xproxy/util.go

Discharges are generally small in number and hence a slice is a more appropriate representation for them than a map. The map was originally used to avoid writing a simple 'Find' function but this has led to conversion to/from maps/slices. This PR uses a slice representation throughout but otherwise has no impact on performance or memory allocations.

v23/flow: use a slice rather than map for representing Discharges.

---

x/ref/runtime/internal/flow/conn/auth_test.go
x/ref/runtime/internal/flow/conn/conn_test.go
x/ref/runtime/internal/flow/conn/handle_message.go

This PR cleans up the logic and documentation for readRemoteAuthLoop. In particular it makes it clear how blessings are formatted as messages and hence how they should be read in terms of those messages. This sets the stage for refactoring how blessings are encoded in a future version of the RPC/flow protocol since this is currently a fairly inefficient portion of the protocol.

x/ref/runtime/internal/flow/conn: cleanup up readRemoteAuthLoop

---

x/ref/runtime/internal/flow/conn/message_pipe.go

This PR saves a few memory allocations by avoiding the use of closures to manage different ciphers.

x/ref/runtime/internal/flow/conn: avoid using closures for managing cipher versions

---

go.mod
go.work
x/ref/aws/go.mod
x/ref/examples/go.mod
x/ref/runtime/internal/rpc/benchmark/go.mod
x/ref/test/compatibility/modules/simple/go.mod

The replace directives from the root go.mod makes it difficult to do a `go install` on the binaries provided by v.io
(https://go.dev/issue/44840 is one place where this is discussed). This commit is trying to fix this by using the Go workspaces added in go 1.18.

Add a go.work and remove the replace directives from go.mod
